// Q: verify BOTH sticks live under raw-CDP multi-touch.
import puppeteer from "puppeteer-core";
import { makeMT } from "./mt.mjs";
const browser = await puppeteer.launch({ protocolTimeout: 600000, executablePath: "/usr/bin/chromium", headless: true, args: ["--no-sandbox", "--disable-gpu", "--enable-unsafe-swiftshader"] });
const phone = await browser.newPage();
await phone.emulate({ viewport: { width: 844, height: 390, isMobile: true, hasTouch: true, deviceScaleFactor: 2 }, userAgent: "Mozilla/5.0 (iPhone)" });
await phone.goto("http://localhost:4179/coldsnap/", { waitUntil: "networkidle0" });
await phone.evaluate(() => localStorage.setItem("coldsnap-screen", "menu"));
await phone.reload({ waitUntil: "networkidle0" });
await phone.waitForSelector('[data-menu="mech"]', { timeout: 15000 });
await phone.tap('[data-menu="mech"]');
await phone.waitForSelector("[data-mech-reissue]", { timeout: 20000 });
await phone.waitForFunction(() => window.__MECHRANGE__ && window.__MECHRANGE__.mech.hull.R[4] > 0.9, { timeout: 20000, polling: 500 });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const mt = await makeMT(phone);
await mt.start(1, 86, 260);
await sleep(200);
await mt.move(1, 86, 224);
await sleep(600);
await mt.start(2, 758, 260);
await sleep(200);
await mt.move(2, 794, 260);
await sleep(800);
console.log("both held:", JSON.stringify(await phone.evaluate(() => window.__MECHRANGE__.dbg())));
await mt.end(2);
await sleep(400);
console.log("right released:", JSON.stringify(await phone.evaluate(() => window.__MECHRANGE__.dbg())));
await mt.end(1);
await browser.close();
