// Q: minimal touch sanity — one stick, then two concurrent.
import puppeteer from "puppeteer-core";
const browser = await puppeteer.launch({ protocolTimeout: 600000, executablePath: "/usr/bin/chromium", headless: true, args: ["--no-sandbox", "--disable-gpu", "--enable-unsafe-swiftshader"] });
const phone = await browser.newPage();
await phone.emulate({ viewport: { width: 844, height: 390, isMobile: true, hasTouch: true, deviceScaleFactor: 2 }, userAgent: "Mozilla/5.0 (iPhone)" });
await phone.goto("http://localhost:4179/coldsnap/", { waitUntil: "networkidle0" });
await phone.evaluate(() => localStorage.setItem("coldsnap-screen", "menu"));
await phone.reload({ waitUntil: "networkidle0" });
await phone.waitForSelector('[data-menu="mech"]', { timeout: 15000 });
await phone.tap('[data-menu="mech"]');
await phone.waitForSelector("[data-mech-reissue]", { timeout: 20000 });
await phone.waitForFunction(() => window.__MECHRANGE__ && window.__MECHRANGE__.mech.hull.R[4] > 0.9, { timeout: 20000, polling: 500 });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
console.log("A: single left-stick drag");
await phone.touchscreen.touchStart(86, 260);
await sleep(300);
await phone.touchscreen.touchMove(86, 224);
await sleep(800);
console.log(JSON.stringify(await phone.evaluate(() => window.__MECHRANGE__.dbg())));
await phone.touchscreen.touchEnd();
await sleep(500);
console.log("B: left held + right added");
await phone.touchscreen.touchStart(86, 260);
await sleep(200);
await phone.touchscreen.touchMove(86, 224);
await sleep(500);
await phone.touchscreen.touchStart(758, 260);
await sleep(200);
await phone.touchscreen.touchMove(794, 260);
await sleep(800);
console.log(JSON.stringify(await phone.evaluate(() => window.__MECHRANGE__.dbg())));
await phone.touchscreen.touchEnd();
await phone.touchscreen.touchEnd();
await browser.close();
